"""
Purchase Order + PurchaseOrderLine.

IMPORTANT (audited rule): confirming a Purchase Order does NOT create
any Journal Entry. A PO is a commitment only; accounting impact only
begins at Vendor Bill confirmation. See docs/architecture.md.

po_no is auto-generated by app/services/sequence_service.py
(format: PO0001).

Owned by: Database Developer.
"""
from sqlalchemy import Column, Integer, String, Numeric, Enum, ForeignKey, Date, DateTime, func
from sqlalchemy.orm import relationship

from app.core.database import Base
from app.models.enums import DocumentStatus


class PurchaseOrder(Base):
    __tablename__ = "purchase_orders"

    id = Column(Integer, primary_key=True, index=True)

    po_no = Column(String(50), unique=True, nullable=False)
    vendor_id = Column(Integer, ForeignKey("contacts.id"), nullable=False)
    po_date = Column(Date, nullable=False)

    status = Column(Enum(DocumentStatus), nullable=False, default=DocumentStatus.DRAFT)

    created_at = Column(DateTime(timezone=True), server_default=func.now())

    vendor = relationship("Contact")
    lines = relationship("PurchaseOrderLine", back_populates="purchase_order",
                          cascade="all, delete-orphan")
    vendor_bill = relationship("VendorBill", back_populates="purchase_order", uselist=False)

    def __repr__(self) -> str:
        return f"<PurchaseOrder id={self.id} po_no={self.po_no} status={self.status}>"


class PurchaseOrderLine(Base):
    __tablename__ = "purchase_order_lines"

    id = Column(Integer, primary_key=True, index=True)

    purchase_order_id = Column(Integer, ForeignKey("purchase_orders.id"), nullable=False)
    product_id = Column(Integer, ForeignKey("products.id"), nullable=False)

    # Analytic Account is assigned per LINE ITEM (audited requirement),
    # not on the document header.
    analytic_account_id = Column(Integer, ForeignKey("analytic_accounts.id"), nullable=True)

    qty = Column(Numeric(12, 2), nullable=False)
    unit_price = Column(Numeric(12, 2), nullable=False)
    total = Column(Numeric(12, 2), nullable=False)  # qty * unit_price

    purchase_order = relationship("PurchaseOrder", back_populates="lines")
    product = relationship("Product")
    analytic_account = relationship("AnalyticAccount")
