from datetime import date
from decimal import Decimal
from typing import List, Optional
from pydantic import BaseModel

from app.models.enums import DocumentStatus, PaymentStatus
from app.schemas.common import ORMBase


class CustomerInvoiceLineCreate(BaseModel):
    product_id: int
    account_id: Optional[int] = None  # defaults to "Sales Income" if omitted
    analytic_account_id: Optional[int] = None
    qty: Decimal
    unit_price: Decimal


class CustomerInvoiceLineResponse(ORMBase):
    id: int
    product_id: int
    account_id: int
    analytic_account_id: Optional[int] = None
    qty: Decimal
    unit_price: Decimal
    total: Decimal


class CustomerInvoiceCreate(BaseModel):
    customer_id: int
    sales_order_id: Optional[int] = None  # set when generated from an SO
    reference: Optional[str] = None
    invoice_date: date
    due_date: Optional[date] = None
    lines: List[CustomerInvoiceLineCreate]
    # invoice_no is auto-generated by sequence_service.py — not accepted from client.


class CustomerInvoiceResponse(ORMBase):
    id: int
    invoice_no: str
    reference: Optional[str] = None
    customer_id: int
    sales_order_id: Optional[int] = None
    invoice_date: date
    due_date: Optional[date] = None
    status: DocumentStatus
    payment_status: PaymentStatus
    lines: List[CustomerInvoiceLineResponse] = []

    # Computed (not a stored column) — populated by the route via
    # payment_service.get_amount_due().
    amount_due: Optional[Decimal] = None
