from datetime import date
from decimal import Decimal
from typing import List, Optional
from pydantic import BaseModel

from app.models.enums import DocumentStatus
from app.schemas.common import ORMBase


class PurchaseOrderLineCreate(BaseModel):
    product_id: int
    analytic_account_id: Optional[int] = None
    qty: Decimal
    unit_price: Decimal
    # total is computed server-side as qty * unit_price — TODO in purchase_service.py


class PurchaseOrderLineResponse(ORMBase):
    id: int
    product_id: int
    analytic_account_id: Optional[int] = None
    qty: Decimal
    unit_price: Decimal
    total: Decimal


class PurchaseOrderCreate(BaseModel):
    vendor_id: int
    po_date: date
    lines: List[PurchaseOrderLineCreate]
    # po_no is auto-generated by sequence_service.py — not accepted from client.


class PurchaseOrderResponse(ORMBase):
    id: int
    po_no: str
    vendor_id: int
    po_date: date
    status: DocumentStatus
    lines: List[PurchaseOrderLineResponse] = []
