from datetime import date
from decimal import Decimal
from typing import List, Optional
from pydantic import BaseModel

from app.models.enums import DocumentStatus
from app.schemas.common import ORMBase


class SalesOrderLineCreate(BaseModel):
    product_id: int
    analytic_account_id: Optional[int] = None
    qty: Decimal
    unit_price: Decimal


class SalesOrderLineResponse(ORMBase):
    id: int
    product_id: int
    analytic_account_id: Optional[int] = None
    qty: Decimal
    unit_price: Decimal
    total: Decimal


class SalesOrderCreate(BaseModel):
    customer_id: int
    so_date: date
    lines: List[SalesOrderLineCreate]
    # so_no is auto-generated by sequence_service.py — not accepted from client.


class SalesOrderResponse(ORMBase):
    id: int
    so_no: str
    customer_id: int
    so_date: date
    status: DocumentStatus
    lines: List[SalesOrderLineResponse] = []
