from datetime import date
from decimal import Decimal
from typing import List, Optional
from pydantic import BaseModel

from app.models.enums import DocumentStatus, PaymentStatus
from app.schemas.common import ORMBase


class VendorBillLineCreate(BaseModel):
    product_id: int
    account_id: Optional[int] = None  # defaults to "Purchase Expense" if omitted
    analytic_account_id: Optional[int] = None
    qty: Decimal
    unit_price: Decimal


class VendorBillLineResponse(ORMBase):
    id: int
    product_id: int
    account_id: int
    analytic_account_id: Optional[int] = None
    qty: Decimal
    unit_price: Decimal
    total: Decimal


class VendorBillCreate(BaseModel):
    vendor_id: int
    purchase_order_id: Optional[int] = None  # set when "Create Bill" is used from a PO
    reference: Optional[str] = None
    bill_date: date
    due_date: Optional[date] = None
    lines: List[VendorBillLineCreate]
    # bill_no is auto-generated by sequence_service.py — not accepted from client.


class VendorBillResponse(ORMBase):
    id: int
    bill_no: str
    reference: Optional[str] = None
    vendor_id: int
    purchase_order_id: Optional[int] = None
    bill_date: date
    due_date: Optional[date] = None
    status: DocumentStatus
    payment_status: PaymentStatus
    lines: List[VendorBillLineResponse] = []

    # TODO (report_service.py or a computed property): amount_due =
    # sum(line.total) - sum(related payments.amount)
